/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/robot.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/robot.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <primitive object={nodes.spine002} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <skinnedMesh
          geometry={nodes.v3001_1.geometry}
          material={materials.Dumb}
          skeleton={nodes.v3001_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.v3001_2.geometry}
          material={materials["Rock n roll racing"]}
          skeleton={nodes.v3001_2.skeleton}
        />
        <skinnedMesh
          geometry={nodes.v3001_3.geometry}
          material={materials["The guy"]}
          skeleton={nodes.v3001_3.skeleton}
        />
        <skinnedMesh
          geometry={nodes.v3001_4.geometry}
          material={materials.BLOOD}
          skeleton={nodes.v3001_4.skeleton}
        />
        <skinnedMesh
          geometry={nodes.v3001_5.geometry}
          material={materials.Stupid}
          skeleton={nodes.v3001_5.skeleton}
        />
        <skinnedMesh
          geometry={nodes.v3001_6.geometry}
          material={materials["Does not work"]}
          skeleton={nodes.v3001_6.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/robot.glb");
